Finished the project
carloshdelreal/building-with-responsive-design pull request #1
Opened 2019-06-20 18:00 UTC by carloshdelreal

all the items are responsive and pretty much as the origina webpage

2019-06-20 18:35 UTC, bellom requested changes
Hi @carloshdelreal @ViriCruz,
You have done a great job, just few things left to have :+1: , which are;
1. The navbar should be fixed just like the original website.
2. Correct the validation error.
**After fixing the issues please send another request to re-review this project.**

Tips:
For every HTML/CSS projects please check your files with the W3 Validator and the CSS Linter

2019-06-20 18:35 UTC, bellom commented on index.html
> +                        <img src="img/tnw.svg"/>
An `img` element must have an alt attribute, except under certain conditions, correct this.

2019-06-20 18:35 UTC, bellom commented on index.html
> +                        <img src="img/stackpath.svg" />
An `img` element must have an alt attribute, except under certain conditions, correct this.

2019-06-21 21:01 UTC, ViriCruz commented
Hi @bellom I was wandering if our project is ready to merge. Let us know please :).

2019-06-22 11:01 UTC, bellom commented
Awesome job guys, kindly submit another code review form....

2019-06-22 17:38 UTC, bellom approved these changes
Hi @carloshdelreal @ViriCruz, 
## Congratulation guys :+1:

2019-06-24 02:32 UTC, merged